### ISSUE TITLE
Help with Regex needed

### ISSUE THREAD

**Issue by JayGray** [Dica-Developer/MTG#24]
@mschaaf
For the filter of cards I need to change how to handle the color filter.
Not all cards (especially the newer) don't have a `color` property anymore.
Now I need a regex to filter cards by `manaCost`.
### Given:
`<String> manaCost = '{2}{R}{U}{C}'`
`<String> manaCost2 = '{U}'`

### Solved:
Current regex to filter by color is:
`/U/g` returns true if test with `manaCost` and `manaCost2`
to filter by more than one color:
`/U|R/g` returns true with `manaCost` and `manaCost2`

### Question:
I want to give the user the option to set some kind of `strict` mode.
Means, if I filter by `U` only `manaCost2` will match or filter by `R && U` nothing will match,
because `manaCost` has more than the given color and `manaCost2` less.
I need an exact match of colors.

Thx

**Comment by mschaaf** [comment]
Is there an order in the mana cost definition of a card, e.g. is always R before U or can it change. Also in case it is stable I see a lot of possible combination which are not optimal to query by regex. How about pre process the cards before moving them to the db and give them an field for every color and set this to true or false. Then querying that with a DB query is much easier and I guess also faster. Is this possible?

**Comment by swalesch** [comment]
Yes the Color has a specific order: universal Mana + (Colorless or (W U B R G))
i don't know if there are any cards with Colorless Mana and a color but i don't think so

**Comment by swalesch** [comment]
http://mtgsalvation.gamepedia.com/Color_Pie#Multicolor
